import type { JobOrderData } from "@/types/job-order";

/**
 * Mock 데이터베이스
 * 다양한 인쇄물 타입 예시 포함
 */
export const mockDatabase: Record<string, JobOrderData> = {
  // 1. 양면 명함
  "1": {
    documentNumber: "202510-BIZ-00431_00",
    orderDate: "2025-10-02",
    clientName: "BIZ",
    orderNumber: "8360443",
    ordererName: "최정희",
    deliveryDate: "2025-10-15",
    deliveryMethod: "택배",
    itemCount: "1 / 1",
    recipientName: "최정희",
    deliveryMemo: "부재시 집앞에 놔주세요.",
    product: {
      productName: "2단접지카드",
      companyProductName: "2단 엽서카드-접이식 엽서카드",
      productionNumber: "30153892",
      productionQuantity: "10 매",
      size: "150x100mm",
      finishedSize: "150x100mm [15.2 X 20.2]",
      specification: {
        productType: "double",
        printSide: "both",
        colorFront: "4도",
        colorBack: "4도",
        paper: "랑데뷰 240g",
        finishing: "무광코팅",
      },
      images: [
        {
          id: "img_front_1",
          url: "https://via.placeholder.com/400x250?text=Front+Design",
          side: "front",
          description: "앞면 디자인",
          width: 1500,
          height: 1000,
        },
        {
          id: "img_back_1",
          url: "https://via.placeholder.com/400x250?text=Back+Design",
          side: "back",
          description: "뒷면 디자인",
          width: 1500,
          height: 1000,
        },
      ],
      postProcessing: [
        {
          id: "post_1",
          name: "형압",
          description: "로고 부분 형압 처리",
          position: "앞면 로고 영역",
          images: [
            {
              id: "post_img_1",
              url: "https://via.placeholder.com/200x150?text=Embossing+Sample",
              description: "형압 참고 이미지",
            },
          ],
        },
      ],
      note: "",
    },
    options: {
      option1: "랑데뷰 240g",
      option2: "흰색 무지봉투(165x115mm)",
      option3: "-",
      option4: "50",
      option5: "-",
      option6: "-",
      option7: "-",
    },
    printDate: "2025년 10월 12일 오후 11:16:38",
    printedBy: "어드민(admin)",
  },

  // 2. 양면 명함 (고급 후가공)
  "2": {
    documentNumber: "202510-SHOP-00532_01",
    orderDate: "2025-10-05",
    clientName: "쉬잇크루",
    orderNumber: "8360789",
    ordererName: "김철수",
    deliveryDate: "2025-10-20",
    deliveryMethod: "직접수령",
    itemCount: "2 / 5",
    recipientName: "김철수",
    deliveryMemo: "오전 배송 부탁드립니다.",
    product: {
      productName: "명함",
      companyProductName: "고급 명함 - 양면 컬러",
      productionNumber: "30154001",
      productionQuantity: "500 매",
      size: "90x50mm",
      finishedSize: "90x50mm",
      specification: {
        productType: "double",
        printSide: "both",
        colorFront: "4도",
        colorBack: "4도",
        paper: "스노우화이트 300g",
        finishing: "UV 코팅",
      },
      images: [
        {
          id: "img_front_1",
          url: "https://via.placeholder.com/360x200?text=Business+Card+Front",
          side: "front",
          description: "명함 앞면",
          width: 900,
          height: 500,
        },
        {
          id: "img_back_1",
          url: "https://via.placeholder.com/360x200?text=Business+Card+Back",
          side: "back",
          description: "명함 뒷면",
          width: 900,
          height: 500,
        },
      ],
      postProcessing: [
        {
          id: "post_1",
          name: "UV 코팅",
          description: "전면 UV 코팅 처리",
          position: "앞면 전체",
        },
        {
          id: "post_2",
          name: "모서리 라운딩",
          description: "4면 라운딩 R3mm",
          position: "모서리",
        },
      ],
      note: "UV 코팅 처리 필요",
    },
    options: {
      option1: "스노우화이트 300g",
      option2: "UV 코팅",
      option3: "양면 4도",
      option4: "100",
      option5: "모서리 라운딩",
      option6: "-",
      option7: "-",
    },
    printDate: "2025년 10월 13일 오후 08:30:15",
    printedBy: "어드민(admin)",
  },

  // 3. 단면 전단지
  "3": {
    documentNumber: "202510-CORP-00891_02",
    orderDate: "2025-10-08",
    clientName: "주식회사 테크노",
    orderNumber: "8361024",
    ordererName: "박영희",
    deliveryDate: "2025-10-25",
    deliveryMethod: "퀵서비스",
    itemCount: "1 / 1",
    recipientName: "박영희",
    deliveryMemo: "급한 물건입니다. 빠른 배송 부탁드립니다.",
    product: {
      productName: "포스터",
      companyProductName: "대형 포스터 - 실사 출력",
      productionNumber: "30154205",
      productionQuantity: "20 매",
      size: "A1 (594x841mm)",
      finishedSize: "A1 (594x841mm)",
      specification: {
        productType: "single",
        printSide: "front_only",
        colorFront: "4도",
        paper: "백색 합지 200g",
        finishing: "무광 코팅",
      },
      images: [
        {
          id: "img_front_1",
          url: "https://via.placeholder.com/594x841?text=Poster+Design",
          side: "front",
          description: "포스터 디자인",
          width: 1782,
          height: 2523,
        },
      ],
      note: "고해상도 이미지 사용, 색상 교정 필요",
    },
    options: {
      option1: "백색 합지 200g",
      option2: "무광 코팅",
      option3: "단면 4도",
      option4: "150",
      option5: "-",
      option6: "-",
      option7: "-",
    },
    printDate: "2025년 10월 13일 오후 09:45:22",
    printedBy: "운영자(operator)",
  },

  // 4. 다중 페이지 - 카탈로그
  "4": {
    documentNumber: "202510-CAT-01234_00",
    orderDate: "2025-10-10",
    clientName: "디자인컴퍼니",
    orderNumber: "8361500",
    ordererName: "이지은",
    deliveryDate: "2025-11-01",
    deliveryMethod: "택배",
    itemCount: "1 / 1",
    recipientName: "이지은",
    deliveryMemo: "포장 튼튼하게 부탁드립니다.",
    product: {
      productName: "카탈로그",
      companyProductName: "제품 카탈로그 32페이지",
      productionNumber: "30154567",
      productionQuantity: "100 부",
      size: "A4 (210x297mm)",
      finishedSize: "A4 (210x297mm)",
      specification: {
        productType: "multi",
        printSide: "both",
        pageCount: 32,
        colorFront: "4도",
        colorBack: "4도",
        paper: "표지: 아트지 250g / 내지: 아트지 150g",
        finishing: "무선철 제책",
        bindingType: "무선철",
      },
      images: [
        {
          id: "img_cover_front",
          url: "https://via.placeholder.com/210x297?text=Cover+Front",
          pageNumber: 1,
          description: "표지 앞면",
          width: 2100,
          height: 2970,
        },
        {
          id: "img_cover_back",
          url: "https://via.placeholder.com/210x297?text=Cover+Back",
          pageNumber: 32,
          description: "표지 뒷면",
          width: 2100,
          height: 2970,
        },
        {
          id: "img_page_2",
          url: "https://via.placeholder.com/210x297?text=Page+2-3",
          pageNumber: 2,
          description: "내지 2-3페이지",
          width: 2100,
          height: 2970,
        },
        {
          id: "img_page_4",
          url: "https://via.placeholder.com/210x297?text=Page+4-5",
          pageNumber: 4,
          description: "내지 4-5페이지",
          width: 2100,
          height: 2970,
        },
      ],
      postProcessing: [
        {
          id: "post_1",
          name: "무선철 제책",
          description: "무선철 방식으로 제책",
          position: "제책",
        },
        {
          id: "post_2",
          name: "표지 코팅",
          description: "표지 유광 코팅 처리",
          position: "표지",
        },
      ],
      note: "표지 코팅 처리, 색상 보정 필요",
    },
    printDate: "2025년 10월 13일 오후 10:30:00",
    printedBy: "어드민(admin)",
  },

  // 5. 다중 페이지 - 팜플렛
  "5": {
    documentNumber: "202510-PAM-05678_01",
    orderDate: "2025-10-12",
    clientName: "이벤트플래너",
    orderNumber: "8361890",
    ordererName: "강민호",
    deliveryDate: "2025-10-28",
    deliveryMethod: "택배",
    itemCount: "1 / 2",
    recipientName: "강민호",
    deliveryMemo: "행사 전날까지 수령 필요",
    product: {
      productName: "팜플렛",
      companyProductName: "3단 접지 팜플렛",
      productionNumber: "30155001",
      productionQuantity: "1,000 부",
      size: "210x297mm",
      finishedSize: "210x99mm (접었을 때)",
      specification: {
        productType: "multi",
        printSide: "both",
        pageCount: 6, // 양면 3단 접지
        colorFront: "4도",
        colorBack: "4도",
        paper: "스노우화이트 200g",
        finishing: "3단 접지",
        bindingType: "접지",
      },
      images: [
        {
          id: "img_outside",
          url: "https://via.placeholder.com/630x297?text=Outside",
          side: "front",
          description: "바깥면 (3단 펼쳤을 때)",
          width: 6300,
          height: 2970,
        },
        {
          id: "img_inside",
          url: "https://via.placeholder.com/630x297?text=Inside",
          side: "back",
          description: "안쪽면 (3단 펼쳤을 때)",
          width: 6300,
          height: 2970,
        },
      ],
      postProcessing: [
        {
          id: "post_1",
          name: "3단 접지",
          description: "3단 접지 가공",
          position: "접지",
        },
      ],
      note: "접지 방향 확인 필요",
    },
    printDate: "2025년 10월 13일 오후 11:00:00",
    printedBy: "어드민(admin)",
  },

  // 6. 후가공 많은 제품 - 패키지
  "6": {
    documentNumber: "202510-PKG-09999_00",
    orderDate: "2025-10-15",
    clientName: "브랜드컴퍼니",
    orderNumber: "8362100",
    ordererName: "최수진",
    deliveryDate: "2025-11-05",
    deliveryMethod: "직접수령",
    itemCount: "1 / 1",
    recipientName: "최수진",
    deliveryMemo: "샘플 먼저 확인 후 생산",
    product: {
      productName: "패키지 박스",
      companyProductName: "고급 제품 패키지",
      productionNumber: "30155500",
      productionQuantity: "500 개",
      size: "150x150x50mm",
      finishedSize: "150x150x50mm (조립 후)",
      specification: {
        productType: "single",
        printSide: "front_only",
        colorFront: "4도",
        paper: "골판지 E골 + 고급 아트지 합지",
        finishing: "다양한 후가공",
      },
      images: [
        {
          id: "img_design",
          url: "https://via.placeholder.com/400x400?text=Package+Design",
          side: "front",
          description: "패키지 전개도",
          width: 4000,
          height: 4000,
        },
        {
          id: "img_mockup",
          url: "https://via.placeholder.com/400x400?text=3D+Mockup",
          description: "3D 목업",
          width: 2000,
          height: 2000,
        },
      ],
      postProcessing: [
        {
          id: "post_1",
          name: "금박",
          description: "로고 부분 금박 처리",
          position: "상단 로고",
          images: [
            {
              id: "post_img_1",
              url: "https://via.placeholder.com/200x100?text=Gold+Foil+Sample",
              description: "금박 샘플",
            },
          ],
        },
        {
          id: "post_2",
          name: "형압",
          description: "엠보싱 처리",
          position: "브랜드명",
          images: [
            {
              id: "post_img_2",
              url: "https://via.placeholder.com/200x100?text=Emboss+Sample",
              description: "형압 샘플",
            },
          ],
        },
        {
          id: "post_3",
          name: "코팅",
          description: "무광 코팅 + 부분 유광",
          position: "전면",
        },
        {
          id: "post_4",
          name: "톰슨",
          description: "톰슨 칼선 가공",
          position: "전개도",
          images: [
            {
              id: "post_img_4",
              url: "https://via.placeholder.com/300x200?text=Die-cut+Template",
              description: "톰슨 도면",
            },
          ],
        },
      ],
      note: "샘플 제작 후 본 생산 진행, 칼선 도면 별도 첨부",
    },
    printDate: "2025년 10월 13일 오후 11:30:00",
    printedBy: "어드민(admin)",
  },
};
