import type { JobOrderData } from "@/types/job-order";

/**
 * Mock 데이터베이스
 * 다양한 인쇄물 타입 예시 포함
 */
export const mockDatabase: Record<string, JobOrderData> = {
  // 1. 책자물 - 무선 제본 책자 (24페이지)
  "1": {
    documentNumber: "202510-BOOK-00431_00",
    orderDate: "2025-10-02",
    clientName: "테크컴퍼니",
    orderNumber: "8360443",
    ordererName: "최정희",
    deliveryDate: "2025-10-15",
    deliveryMethod: "택배",
    itemCount: "1 / 1",
    recipientName: "최정희",
    deliveryMemo: "부재시 집앞에 놔주세요.",
    product: {
      productName: "무선 제본 책자",
      companyProductName: "무선 제본 책자 24페이지",
      productionNumber: "30153892",
      productionQuantity: "200 부",
      size: "A5 (148x210mm)",
      finishedSize: "A5 (148x210mm)",
      specification: {
        productType: "multi",
        printSide: "both",
        pageCount: 24,
        colorFront: "4도",
        colorBack: "4도",
        paper: "표지: 아트지 250g / 내지: 백색 모조지 100g",
        finishing: "무선 제본",
        bindingType: "무선철",
      },
      images: [
        {
          id: "img_page_1",
          url: "https://placehold.co/210x210/cccccc/333333?text=Cover",
          pageNumber: 1,
          description: "표지 (1페이지)",
          width: 2100,
          height: 2100,
        },
        {
          id: "img_page_2",
          url: "https://placehold.co/210x210?text=Page+2",
          pageNumber: 2,
          description: "내지 2페이지",
          width: 2100,
          height: 2100,
        },
      ],
      postProcessing: [
        {
          id: "post_1",
          name: "무선 제본",
          description: "무선철 방식 제본",
          position: "제책",
        },
        {
          id: "post_2",
          name: "표지 코팅",
          description: "표지 양면 무광 코팅",
          position: "표지",
        },
      ],
      note: "무선 제본, 표지 코팅 처리",
    },
    options: {
      option1: "표지: 아트지 250g",
      option2: "내지: 백색 모조지 100g",
      option3: "양면 4도",
      option4: "150",
      option5: "무선 제본",
      option6: "표지 무광 코팅",
      option7: "-",
    },
    printDate: "2025년 10월 12일 오후 11:16:38",
    printedBy: "어드민(admin)",
  },

  // 2. 명함 - 고급지 명함 (양면 UV코팅)
  "2": {
    documentNumber: "202510-CARD-00532_01",
    orderDate: "2025-10-05",
    clientName: "쉬잇크루",
    orderNumber: "8360789",
    ordererName: "김철수",
    deliveryDate: "2025-10-20",
    deliveryMethod: "직접수령",
    itemCount: "2 / 5",
    recipientName: "김철수",
    deliveryMemo: "오전 배송 부탁드립니다.",
    product: {
      productName: "고급지 명함",
      companyProductName: "고급지 명함 - 양면 UV코팅",
      productionNumber: "30154001",
      productionQuantity: "500 매",
      size: "90x50mm",
      finishedSize: "90x50mm",
      specification: {
        productType: "double",
        printSide: "both",
        colorFront: "4도",
        colorBack: "4도",
        paper: "스노우화이트 300g",
        finishing: "UV 코팅",
      },
      images: [
        {
          id: "img_front_1",
          url: "https://placehold.co/360x200?text=Business+Card+Front",
          side: "front",
          description: "명함 앞면",
          width: 900,
          height: 500,
        },
        {
          id: "img_back_1",
          url: "https://placehold.co/360x200?text=Business+Card+Back",
          side: "back",
          description: "명함 뒷면",
          width: 900,
          height: 500,
        },
      ],
      postProcessing: [
        {
          id: "post_1",
          name: "UV 코팅",
          description: "전면 UV 코팅 처리",
          position: "앞면 전체",
        },
        {
          id: "post_2",
          name: "모서리 라운딩",
          description: "4면 라운딩 R3mm",
          position: "모서리",
        },
      ],
      note: "UV 코팅 처리 필요",
    },
    options: {
      option1: "스노우화이트 300g",
      option2: "UV 코팅",
      option3: "양면 4도",
      option4: "100",
      option5: "모서리 라운딩",
      option6: "-",
      option7: "-",
    },
    printDate: "2025년 10월 13일 오후 08:30:15",
    printedBy: "어드민(admin)",
  },

  // 3. 대형 실사 출력 - 현수막
  "3": {
    documentNumber: "202510-BANNER-00891_02",
    orderDate: "2025-10-08",
    clientName: "주식회사 테크노",
    orderNumber: "8361024",
    ordererName: "박영희",
    deliveryDate: "2025-10-25",
    deliveryMethod: "퀵서비스",
    itemCount: "1 / 1",
    recipientName: "박영희",
    deliveryMemo: "급한 물건입니다. 빠른 배송 부탁드립니다.",
    product: {
      productName: "현수막",
      companyProductName: "실사출력 현수막",
      productionNumber: "30154205",
      productionQuantity: "1 개",
      size: "3000x1000mm",
      finishedSize: "3000x1000mm",
      specification: {
        productType: "single",
        printSide: "front_only",
        colorFront: "4도",
        paper: "현수막 천 (450g)",
        finishing: "양쪽 고리 가공",
      },
      images: [
        {
          id: "img_front_1",
          url: "https://placehold.co/3000x1000?text=Banner+Design",
          side: "front",
          description: "현수막 디자인",
          width: 3000,
          height: 1000,
        },
      ],
      note: "고해상도 이미지 사용, 양쪽 고리 가공 필수",
    },
    options: {
      option1: "현수막 천 (450g)",
      option2: "양쪽 고리 가공",
      option3: "단면 4도",
      option4: "1",
      option5: "실사 출력",
      option6: "-",
      option7: "-",
    },
    printDate: "2025년 10월 13일 오후 09:45:22",
    printedBy: "운영자(operator)",
  },

  // 4. 책자물 - 윤전 인쇄 책자 (32페이지 컬러)
  "4": {
    documentNumber: "202510-BOOK-01234_00",
    orderDate: "2025-10-10",
    clientName: "디자인컴퍼니",
    orderNumber: "8361500",
    ordererName: "이지은",
    deliveryDate: "2025-11-01",
    deliveryMethod: "택배",
    itemCount: "1 / 1",
    recipientName: "이지은",
    deliveryMemo: "포장 튼튼하게 부탁드립니다.",
    product: {
      productName: "윤전 인쇄 책자",
      companyProductName: "윤전 컬러 인쇄 책자 32페이지",
      productionNumber: "30154567",
      productionQuantity: "100 부",
      size: "A4 (210x297mm)",
      finishedSize: "A4 (210x297mm)",
      specification: {
        productType: "multi",
        printSide: "both",
        pageCount: 32,
        colorFront: "4도",
        colorBack: "4도",
        paper: "표지: 아트지 250g / 내지: 아트지 150g",
        finishing: "무선철 제책",
        bindingType: "무선철",
      },
      images: [
        {
          id: "img_cover_front",
          url: "https://placehold.co/210x297?text=Cover+Front",
          pageNumber: 1,
          description: "표지 앞면",
          width: 2100,
          height: 2970,
        },
        {
          id: "img_cover_back",
          url: "https://placehold.co/210x297?text=Cover+Back",
          pageNumber: 32,
          description: "표지 뒷면",
          width: 2100,
          height: 2970,
        },
        {
          id: "img_page_2",
          url: "https://placehold.co/210x297?text=Page+2-3",
          pageNumber: 2,
          description: "내지 2-3페이지",
          width: 2100,
          height: 2970,
        },
        {
          id: "img_page_4",
          url: "https://placehold.co/210x297?text=Page+4-5",
          pageNumber: 4,
          description: "내지 4-5페이지",
          width: 2100,
          height: 2970,
        },
      ],
      postProcessing: [
        {
          id: "post_1",
          name: "무선철 제책",
          description: "무선철 방식으로 제책",
          position: "제책",
        },
        {
          id: "post_2",
          name: "표지 코팅",
          description: "표지 유광 코팅 처리",
          position: "표지",
        },
      ],
      note: "표지 코팅 처리, 색상 보정 필요",
    },
    printDate: "2025년 10월 13일 오후 10:30:00",
    printedBy: "어드민(admin)",
  },

  // 5. 홍보물 - 삼단접지 리플렛
  "5": {
    documentNumber: "202510-FLYER-05678_01",
    orderDate: "2025-10-12",
    clientName: "이벤트플래너",
    orderNumber: "8361890",
    ordererName: "강민호",
    deliveryDate: "2025-10-28",
    deliveryMethod: "택배",
    itemCount: "1 / 2",
    recipientName: "강민호",
    deliveryMemo: "행사 전날까지 수령 필요",
    product: {
      productName: "삼단접지 리플렛",
      companyProductName: "3단 접지 홍보 리플렛",
      productionNumber: "30155001",
      productionQuantity: "1,000 부",
      size: "210x297mm",
      finishedSize: "210x99mm (접었을 때)",
      specification: {
        productType: "multi",
        printSide: "both",
        pageCount: 6, // 양면 3단 접지
        colorFront: "4도",
        colorBack: "4도",
        paper: "스노우화이트 200g",
        finishing: "3단 접지",
        bindingType: "접지",
      },
      images: [
        {
          id: "img_outside",
          url: "https://placehold.co/630x297?text=Outside",
          side: "front",
          description: "바깥면 (3단 펼쳤을 때)",
          width: 6300,
          height: 2970,
        },
        {
          id: "img_inside",
          url: "https://placehold.co/630x297?text=Inside",
          side: "back",
          description: "안쪽면 (3단 펼쳤을 때)",
          width: 6300,
          height: 2970,
        },
      ],
      postProcessing: [
        {
          id: "post_1",
          name: "3단 접지",
          description: "3단 접지 가공",
          position: "접지",
        },
      ],
      note: "접지 방향 확인 필요",
    },
    printDate: "2025년 10월 13일 오후 11:00:00",
    printedBy: "어드민(admin)",
  },

  // 6. 책자물 - 스프링 제본 책자 (보고서용)
  "6": {
    documentNumber: "202510-BOOK-09999_00",
    orderDate: "2025-10-15",
    clientName: "브랜드컴퍼니",
    orderNumber: "8362100",
    ordererName: "최수진",
    deliveryDate: "2025-11-05",
    deliveryMethod: "직접수령",
    itemCount: "1 / 1",
    recipientName: "최수진",
    deliveryMemo: "보고서 용도로 사용",
    product: {
      productName: "스프링 제본 책자",
      companyProductName: "스프링 제본 보고서 40페이지",
      productionNumber: "30155500",
      productionQuantity: "50 부",
      size: "A4 (210x297mm)",
      finishedSize: "A4 (210x297mm)",
      specification: {
        productType: "multi",
        printSide: "both",
        pageCount: 40,
        colorFront: "4도",
        colorBack: "흑백",
        paper: "표지: 투명 PVC / 내지: 백색 모조지 80g",
        finishing: "스프링 제본",
        bindingType: "스프링",
      },
      images: [
        {
          id: "img_cover",
          url: "https://placehold.co/210x297?text=Cover",
          pageNumber: 1,
          description: "표지 (투명 PVC)",
          width: 2100,
          height: 2970,
        },
        {
          id: "img_page_2",
          url: "https://placehold.co/210x297?text=Page+2",
          pageNumber: 2,
          description: "내지 샘플",
          width: 2100,
          height: 2970,
        },
      ],
      postProcessing: [
        {
          id: "post_1",
          name: "스프링 제본",
          description: "흰색 플라스틱 스프링 제본",
          position: "제책",
        },
      ],
      note: "투명 PVC 표지, 스프링 제본",
    },
    printDate: "2025년 10월 13일 오후 11:30:00",
    printedBy: "어드민(admin)",
  },

  // 7. 책자물 - 토너/잉크젯 책자 (16페이지)
  "7": {
    documentNumber: "202510-BOOK-12345_00",
    orderDate: "2025-10-16",
    clientName: "출판사컴퍼니",
    orderNumber: "8362500",
    ordererName: "홍길동",
    deliveryDate: "2025-11-10",
    deliveryMethod: "택배",
    itemCount: "1 / 1",
    recipientName: "홍길동",
    deliveryMemo: "파손 주의",
    product: {
      productName: "토너/잉크젯 책자",
      companyProductName: "중철제책 토너 인쇄 책자 16페이지",
      productionNumber: "30156000",
      productionQuantity: "300 부",
      size: "A5 (148x210mm)",
      finishedSize: "A5 (148x210mm)",
      specification: {
        productType: "multi",
        printSide: "both",
        pageCount: 16,
        colorFront: "4도",
        colorBack: "4도",
        paper: "표지: 아트지 200g / 내지: 백색 모조지 100g",
        finishing: "중철 제책",
        bindingType: "중철",
      },
      images: [
        {
          id: "img_page_1",
          url: "https://placehold.co/148x210?text=Page+1",
          pageNumber: 1,
          description: "표지 앞면 (1페이지)",
          width: 1480,
          height: 2100,
        },
        {
          id: "img_page_2",
          url: "https://placehold.co/148x210?text=Page+2",
          pageNumber: 2,
          description: "내지 2페이지",
          width: 1480,
          height: 2100,
        },
        {
          id: "img_page_3",
          url: "https://placehold.co/148x210?text=Page+3",
          pageNumber: 3,
          description: "내지 3페이지",
          width: 1480,
          height: 2100,
        },
        {
          id: "img_page_4",
          url: "https://placehold.co/148x210?text=Page+4",
          pageNumber: 4,
          description: "내지 4페이지",
          width: 1480,
          height: 2100,
        },
        {
          id: "img_page_5",
          url: "https://placehold.co/148x210?text=Page+5",
          pageNumber: 5,
          description: "내지 5페이지",
          width: 1480,
          height: 2100,
        },
        {
          id: "img_page_6",
          url: "https://placehold.co/148x210?text=Page+6",
          pageNumber: 6,
          description: "내지 6페이지",
          width: 1480,
          height: 2100,
        },
        {
          id: "img_page_7",
          url: "https://placehold.co/148x210?text=Page+7",
          pageNumber: 7,
          description: "내지 7페이지",
          width: 1480,
          height: 2100,
        },
        {
          id: "img_page_8",
          url: "https://placehold.co/148x210?text=Page+8",
          pageNumber: 8,
          description: "내지 8페이지 (센터 좌)",
          width: 1480,
          height: 2100,
        },
        {
          id: "img_page_9",
          url: "https://placehold.co/148x210?text=Page+9",
          pageNumber: 9,
          description: "내지 9페이지 (센터 우)",
          width: 1480,
          height: 2100,
        },
        {
          id: "img_page_10",
          url: "https://placehold.co/148x210?text=Page+10",
          pageNumber: 10,
          description: "내지 10페이지",
          width: 1480,
          height: 2100,
        },
        {
          id: "img_page_11",
          url: "https://placehold.co/148x210?text=Page+11",
          pageNumber: 11,
          description: "내지 11페이지",
          width: 1480,
          height: 2100,
        },
        {
          id: "img_page_12",
          url: "https://placehold.co/148x210?text=Page+12",
          pageNumber: 12,
          description: "내지 12페이지",
          width: 1480,
          height: 2100,
        },
        {
          id: "img_page_13",
          url: "https://placehold.co/148x210?text=Page+13",
          pageNumber: 13,
          description: "내지 13페이지",
          width: 1480,
          height: 2100,
        },
        {
          id: "img_page_14",
          url: "https://placehold.co/148x210?text=Page+14",
          pageNumber: 14,
          description: "내지 14페이지",
          width: 1480,
          height: 2100,
        },
        {
          id: "img_page_15",
          url: "https://placehold.co/148x210?text=Page+15",
          pageNumber: 15,
          description: "내지 15페이지",
          width: 1480,
          height: 2100,
        },
        {
          id: "img_page_16",
          url: "https://placehold.co/148x210?text=Page+16",
          pageNumber: 16,
          description: "표지 뒷면 (16페이지)",
          width: 1480,
          height: 2100,
        },
      ],
      postProcessing: [
        {
          id: "post_1",
          name: "중철 제책",
          description: "중철 방식으로 제책 (스테이플러)",
          position: "제책",
        },
        {
          id: "post_2",
          name: "표지 코팅",
          description: "표지 양면 무광 코팅",
          position: "표지",
        },
      ],
      note: "중철 제책, 표지 코팅 필수",
    },
    options: {
      option1: "표지: 아트지 200g",
      option2: "내지: 백색 모조지 100g",
      option3: "양면 4도",
      option4: "200",
      option5: "중철 제책",
      option6: "표지 무광 코팅",
      option7: "-",
    },
    printDate: "2025년 10월 13일 오후 11:45:00",
    printedBy: "어드민(admin)",
  },

  // 8. 책자물 - 사철 제본 책자 (48페이지)
  "8": {
    documentNumber: "202510-BOOK-67890_00",
    orderDate: "2025-10-17",
    clientName: "교육기관",
    orderNumber: "8362800",
    ordererName: "김선생",
    deliveryDate: "2025-11-15",
    deliveryMethod: "택배",
    itemCount: "1 / 3",
    recipientName: "김선생",
    deliveryMemo: "교육 자료이므로 깔끔하게 포장 부탁드립니다.",
    product: {
      productName: "사철 제본 책자",
      companyProductName: "사철 제본 책자 48페이지",
      productionNumber: "30156200",
      productionQuantity: "500 부",
      size: "B5 (182x257mm)",
      finishedSize: "B5 (182x257mm)",
      specification: {
        productType: "multi",
        printSide: "both",
        pageCount: 48,
        colorFront: "4도",
        colorBack: "1도",
        paper: "표지: 스노우화이트 250g / 내지: 백색 모조지 80g",
        finishing: "사철 제본",
        bindingType: "사철",
      },
      images: [
        // 표지
        {
          id: "img_cover_front",
          url: "https://placehold.co/182x257?text=Cover",
          pageNumber: 1,
          pageType: "cover_front",
          description: "표지",
          width: 1820,
          height: 2570,
        },
        // 속지 1~46페이지 (pageNumber 2~47)
        {
          id: "img_page_2",
          url: "https://placehold.co/182x257?text=P1",
          pageNumber: 2,
          pageType: "inside",
          description: "1페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_3",
          url: "https://placehold.co/182x257?text=P2",
          pageNumber: 3,
          pageType: "inside",
          description: "2페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_4",
          url: "https://placehold.co/182x257?text=P3",
          pageNumber: 4,
          pageType: "inside",
          description: "3페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_5",
          url: "https://placehold.co/182x257?text=P4",
          pageNumber: 5,
          pageType: "inside",
          description: "4페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_6",
          url: "https://placehold.co/182x257?text=P5",
          pageNumber: 6,
          pageType: "inside",
          description: "5페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_7",
          url: "https://placehold.co/182x257?text=P6",
          pageNumber: 7,
          pageType: "inside",
          description: "6페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_8",
          url: "https://placehold.co/182x257?text=P7",
          pageNumber: 8,
          pageType: "inside",
          description: "7페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_9",
          url: "https://placehold.co/182x257?text=P8",
          pageNumber: 9,
          pageType: "inside",
          description: "8페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_10",
          url: "https://placehold.co/182x257?text=P9",
          pageNumber: 10,
          pageType: "inside",
          description: "9페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_11",
          url: "https://placehold.co/182x257?text=P10",
          pageNumber: 11,
          pageType: "inside",
          description: "10페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_12",
          url: "https://placehold.co/182x257?text=P11",
          pageNumber: 12,
          pageType: "inside",
          description: "11페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_13",
          url: "https://placehold.co/182x257?text=P12",
          pageNumber: 13,
          pageType: "inside",
          description: "12페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_14",
          url: "https://placehold.co/182x257?text=P13",
          pageNumber: 14,
          pageType: "inside",
          description: "13페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_15",
          url: "https://placehold.co/182x257?text=P14",
          pageNumber: 15,
          pageType: "inside",
          description: "14페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_16",
          url: "https://placehold.co/182x257?text=P15",
          pageNumber: 16,
          pageType: "inside",
          description: "15페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_17",
          url: "https://placehold.co/182x257?text=P16",
          pageNumber: 17,
          pageType: "inside",
          description: "16페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_18",
          url: "https://placehold.co/182x257?text=P17",
          pageNumber: 18,
          pageType: "inside",
          description: "17페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_19",
          url: "https://placehold.co/182x257?text=P18",
          pageNumber: 19,
          pageType: "inside",
          description: "18페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_20",
          url: "https://placehold.co/182x257?text=P19",
          pageNumber: 20,
          pageType: "inside",
          description: "19페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_21",
          url: "https://placehold.co/182x257?text=P20",
          pageNumber: 21,
          pageType: "inside",
          description: "20페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_22",
          url: "https://placehold.co/182x257?text=P21",
          pageNumber: 22,
          pageType: "inside",
          description: "21페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_23",
          url: "https://placehold.co/182x257?text=P22",
          pageNumber: 23,
          pageType: "inside",
          description: "22페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_24",
          url: "https://placehold.co/182x257?text=P23",
          pageNumber: 24,
          pageType: "inside",
          description: "23페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_25",
          url: "https://placehold.co/182x257?text=P24",
          pageNumber: 25,
          pageType: "inside",
          description: "24페이지 (센터)",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_26",
          url: "https://placehold.co/182x257?text=P25",
          pageNumber: 26,
          pageType: "inside",
          description: "25페이지 (센터)",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_27",
          url: "https://placehold.co/182x257?text=P26",
          pageNumber: 27,
          pageType: "inside",
          description: "26페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_28",
          url: "https://placehold.co/182x257?text=P27",
          pageNumber: 28,
          pageType: "inside",
          description: "27페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_29",
          url: "https://placehold.co/182x257?text=P28",
          pageNumber: 29,
          pageType: "inside",
          description: "28페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_30",
          url: "https://placehold.co/182x257?text=P29",
          pageNumber: 30,
          pageType: "inside",
          description: "29페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_31",
          url: "https://placehold.co/182x257?text=P30",
          pageNumber: 31,
          pageType: "inside",
          description: "30페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_32",
          url: "https://placehold.co/182x257?text=P31",
          pageNumber: 32,
          pageType: "inside",
          description: "31페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_33",
          url: "https://placehold.co/182x257?text=P32",
          pageNumber: 33,
          pageType: "inside",
          description: "32페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_34",
          url: "https://placehold.co/182x257?text=P33",
          pageNumber: 34,
          pageType: "inside",
          description: "33페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_35",
          url: "https://placehold.co/182x257?text=P34",
          pageNumber: 35,
          pageType: "inside",
          description: "34페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_36",
          url: "https://placehold.co/182x257?text=P35",
          pageNumber: 36,
          pageType: "inside",
          description: "35페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_37",
          url: "https://placehold.co/182x257?text=P36",
          pageNumber: 37,
          pageType: "inside",
          description: "36페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_38",
          url: "https://placehold.co/182x257?text=P37",
          pageNumber: 38,
          pageType: "inside",
          description: "37페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_39",
          url: "https://placehold.co/182x257?text=P38",
          pageNumber: 39,
          pageType: "inside",
          description: "38페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_40",
          url: "https://placehold.co/182x257?text=P39",
          pageNumber: 40,
          pageType: "inside",
          description: "39페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_41",
          url: "https://placehold.co/182x257?text=P40",
          pageNumber: 41,
          pageType: "inside",
          description: "40페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_42",
          url: "https://placehold.co/182x257?text=P41",
          pageNumber: 42,
          pageType: "inside",
          description: "41페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_43",
          url: "https://placehold.co/182x257?text=P42",
          pageNumber: 43,
          pageType: "inside",
          description: "42페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_44",
          url: "https://placehold.co/182x257?text=P43",
          pageNumber: 44,
          pageType: "inside",
          description: "43페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_45",
          url: "https://placehold.co/182x257?text=P44",
          pageNumber: 45,
          pageType: "inside",
          description: "44페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_46",
          url: "https://placehold.co/182x257?text=P45",
          pageNumber: 46,
          pageType: "inside",
          description: "45페이지",
          width: 1820,
          height: 2570,
        },
        {
          id: "img_page_47",
          url: "https://placehold.co/182x257?text=P46",
          pageNumber: 47,
          pageType: "inside",
          description: "46페이지",
          width: 1820,
          height: 2570,
        },
        // 뒷표지
        {
          id: "img_cover_back",
          url: "https://placehold.co/182x257?text=Back",
          pageNumber: 48,
          pageType: "cover_back",
          description: "뒷표지",
          width: 1820,
          height: 2570,
        },
      ],
      postProcessing: [
        {
          id: "post_1",
          name: "사철 제본",
          description: "사철 제본 방식으로 제책 (실로 묶음)",
          position: "제책",
        },
        {
          id: "post_2",
          name: "표지 코팅",
          description: "표지 유광 코팅",
          position: "표지",
        },
      ],
      note: "사철 제본 제책, 표지 유광 코팅, 내지는 흑백 인쇄",
    },
    options: {
      option1: "표지: 스노우화이트 250g",
      option2: "내지: 백색 모조지 80g",
      option3: "표지 4도 / 내지 흑백",
      option4: "300",
      option5: "사철 제본",
      option6: "표지 유광 코팅",
      option7: "-",
    },
    printDate: "2025년 10월 13일 오후 11:50:00",
    printedBy: "어드민(admin)",
  },
};
